config/routes.rb
Fitkids::Application.routes.draw do

  resources :avatars

  devise_for :watchers

  devise_for :children, :controllers => { :sessions => "children/sessions" }

  get "home/index"

  devise_for :users

  resources :child_guardian_relationships do
    resources :users
  end

  resources :users do
    get :child_profile, on: :collection
    get :watcher_profile, on: :collection
    get :sanitized_child_profile, on: :collection
    resources :daily_diets do
      resources :diet_plans
    end
  end

  resources :exercise_reps

  resources :articles

  resources :diet_plans

  resources :daily_diets

  resources :leaderboards do
    get :index_children, on: :collection
  end

  post '/users/increment_exercise'
  post '/users/increment_carbs'
  post '/users/increment_fruit'
  post '/users/increment_prot'
  post '/users/increment_sweets'
  post '/users/increment_veggies'
  post '/users/increment_water'
  post '/users/get_daily_diet'

  root :to => 'home#index'

	

end

app/models/leaderboard.rb
class Leaderboard < ActiveRecord::Base
  attr_accessible :age_group, :board_type
  has_many :children, inverse_of: :leaderboard
  belongs_to :exercise, inverse_of: :leaderboards
end

app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  # GET /leaderboards
  # GET /leaderboards.json

  helper_method :sort_column, :sort_direction
  
  def index
    @leaderboards = Leaderboard.all
    @users = User.where(:type => "Child").order(:level)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leaderboards }
    end
  end

  def index_children
    #@users = User.where(:type => "Child").order(:level)
    @users = User.where(:type => "Child").order(sort_column + " " + sort_direction)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leaderboards }
    end
  end

  # GET /leaderboards/1
  # GET /leaderboards/1.json
  def show
    @leaderboard = Leaderboard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @leaderboard }
    end
  end

  # GET /leaderboards/new
  # GET /leaderboards/new.json
  def new
    @leaderboard = Leaderboard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @leaderboard }
    end
  end

  # GET /leaderboards/1/edit
  def edit
    @leaderboard = Leaderboard.find(params[:id])
  end

  # POST /leaderboards
  # POST /leaderboards.json
  def create
    @leaderboard = Leaderboard.new(params[:leaderboard])

    respond_to do |format|
      if @leaderboard.save
        format.html { redirect_to @leaderboard, notice: 'Leaderboard was successfully created.' }
        format.json { render json: @leaderboard, status: :created, location: @leaderboard }
      else
        format.html { render action: "new" }
        format.json { render json: @leaderboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leaderboards/1
  # PUT /leaderboards/1.json
  def update
    @leaderboard = Leaderboard.find(params[:id])

    respond_to do |format|
      if @leaderboard.update_attributes(params[:leaderboard])
        format.html { redirect_to @leaderboard, notice: 'Leaderboard was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @leaderboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leaderboards/1
  # DELETE /leaderboards/1.json
  def destroy
    @leaderboard = Leaderboard.find(params[:id])
    @leaderboard.destroy

    respond_to do |format|
      format.html { redirect_to leaderboards_url }
      format.json { head :no_content }
    end
  end

  private

  def sort_column
    User.column_names.include?(params[:sort]) ? params[:sort] : "level"
    params[:sort] || "level"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
end

app/views/leaderboards/_form.html.erb
<%= form_for(@leaderboard) do |f| %>
  <% if @leaderboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@leaderboard.errors.count, "error") %> prohibited this leaderboard from being saved:</h2>

      <ul>
      <% @leaderboard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :board_type %><br />
    <%= f.text_field :board_type %>
  </div>
  <div class="field">
    <%= f.label :age_group %><br />
    <%= f.number_field :age_group %>
  </div>
  <div class="field">
    <%= f.label :exercise %><br />
    <%= f.text_field :exercise %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leaderboards/edit.html.erb
<h1>Editing leaderboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @leaderboard %> |
<%= link_to 'Back', leaderboards_path %>

app/views/leaderboards/index.html.erb
<h1>Listing leaderboards</h1>

<table>
  <tr>
    <th>Board type</th>
    <th>Age group</th>
    <th>Exercise</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @leaderboards.each do |leaderboard| %>
  <tr>
    <td><%= leaderboard.board_type %></td>
    <td><%= leaderboard.age_group %></td>
    <td><%= leaderboard.exercise %></td>
    <td><%= link_to 'Show', leaderboard %></td>
    <td><%= link_to 'Edit', edit_leaderboard_path(leaderboard) %></td>
    <td><%= link_to 'Destroy', leaderboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Leaderboard', new_leaderboard_path %>

app/views/leaderboards/index_children.html.erb
<h2>Welcome to the Leaderboards!</h2>
<br/>

<table>
  <tr>
    <th></th>
    <th><%= sorter "Name" %></th>
    <th><%= sorter "Level"%></th>
    <th><%= sorter "Points"%></th>
    <th><%= sorter "food_score" , "Diet Score" %></th>
    <th><%= sorter "exercise_done" , "Ex Score" %></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td><div><%= image_tag(user.avatar.image_name, size:"75x50") %></div></td>
    <td><div><%= user.name %></div></td>
    <td><div><%= user.level %></div></td>
    <td><div><%= user.points %></div></td>
    <td><div><%= user.food_score %></div></td>
    <td><div><%= user.exercise_done %></div></td>
  </tr>
<% end %>
</table>

<br />

app/views/leaderboards/new.html.erb
<h1>New leaderboard</h1>

<%= render 'form' %>

<%= link_to 'Back', leaderboards_path %>

app/views/leaderboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Board type:</b>
  <%= @leaderboard.board_type %>
</p>

<p>
  <b>Age group:</b>
  <%= @leaderboard.age_group %>
</p>

<p>
  <b>Exercise:</b>
  <%= @leaderboard.exercise %>
</p>


<%= link_to 'Edit', edit_leaderboard_path(@leaderboard) %> |
<%= link_to 'Back', leaderboards_path %>