config/routes.rb
Fitkids::Application.routes.draw do

  resources :avatars

  devise_for :watchers

  devise_for :children, :controllers => { :sessions => "children/sessions" }

  get "home/index"

  devise_for :users

  resources :child_guardian_relationships do
    resources :users
  end

  resources :users do
    get :child_profile, on: :collection
    get :watcher_profile, on: :collection
    get :sanitized_child_profile, on: :collection
    resources :daily_diets do
      resources :diet_plans
    end
  end

  resources :exercise_reps

  resources :articles

  resources :diet_plans

  resources :daily_diets

  resources :leaderboards do
    get :index_children, on: :collection
  end

  post '/users/increment_exercise'
  post '/users/increment_carbs'
  post '/users/increment_fruit'
  post '/users/increment_prot'
  post '/users/increment_sweets'
  post '/users/increment_veggies'
  post '/users/increment_water'
  post '/users/get_daily_diet'

  root :to => 'home#index'

	

end

app/models/diet_plan.rb
class DietPlan < ActiveRecord::Base
  attr_accessible :carbs_serv, :fruit_serv, :prot_serv, :sweets_serv, :veggie_serv, :water_serv, :diet_name, :day_made
  has_many :daily_diets, inverse_of: :diet_plan

  def get_total
  	@total_servings = self.carbs_serv + self.fruit_serv + self.prot_serv + self.sweets_serv + self.veggie_serv + self.water_serv
  	return @total_servings
  end
end

app/controllers/diet_plans_controller.rb
class DietPlansController < ApplicationController
  # GET /diet_plans
  # GET /diet_plans.json
  def index
    @diet_plans = DietPlan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @diet_plans }
    end
  end

  # GET /diet_plans/1
  # GET /diet_plans/1.json
  def show
    @diet_plan = DietPlan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @diet_plan }
    end
  end

  # GET /diet_plans/new
  # GET /diet_plans/new.json
  def new
    @diet_plan = DietPlan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @diet_plan }
    end
  end

  # GET /diet_plans/1/edit
  def edit
    @diet_plan = DietPlan.find(params[:id])
  end

  # POST /diet_plans
  # POST /diet_plans.json
  def create
    @diet_plan = DietPlan.new(params[:diet_plan])

    respond_to do |format|
      if @diet_plan.save
        format.html { redirect_to @diet_plan, notice: 'Diet plan was successfully created.' }
        format.json { render json: @diet_plan, status: :created, location: @diet_plan }
      else
        format.html { render action: "new" }
        format.json { render json: @diet_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /diet_plans/1
  # PUT /diet_plans/1.json
  def update
    @diet_plan = DietPlan.find(params[:id])

    respond_to do |format|
      if @diet_plan.update_attributes(params[:diet_plan])
        format.html { redirect_to @diet_plan, notice: 'Diet plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @diet_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diet_plans/1
  # DELETE /diet_plans/1.json
  def destroy
    @diet_plan = DietPlan.find(params[:id])
    @diet_plan.destroy

    respond_to do |format|
      format.html { redirect_to diet_plans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/diet_plans_helper.rb
module DietPlansHelper
end

app/views/diet_plans/_form.html.erb
<%= form_for(@diet_plan) do |f| %>
  <% if @diet_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diet_plan.errors.count, "error") %> prohibited this diet_plan from being saved:</h2>

      <ul>
      <% @diet_plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :diet_name %><br />
    <%= f.text_field :diet_name %>
  </div>
  <div class="field">
    <%= f.label :veggie_serv %><br />
    <%= f.number_field :veggie_serv %>
  </div>
  <div class="field">
    <%= f.label :prot_serv %><br />
    <%= f.number_field :prot_serv %>
  </div>
  <div class="field">
    <%= f.label :carbs_serv %><br />
    <%= f.number_field :carbs_serv %>
  </div>
  <div class="field">
    <%= f.label :fruit_serv %><br />
    <%= f.number_field :fruit_serv %>
  </div>
  <div class="field">
    <%= f.label :water_serv %><br />
    <%= f.number_field :water_serv %>
  </div>
  <div class="field">
    <%= f.label :sweets_serv %><br />
    <%= f.number_field :sweets_serv %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diet_plans/edit.html.erb
<h1>Editing diet_plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @diet_plan %> |
<%= link_to 'Back', diet_plans_path %>

app/views/diet_plans/index.html.erb
<h1>Listing Diet Plans</h1>

<table>
  <tr>
		<th>Diet name</th>
    <th>Veggie serv</th>
    <th>Prot serv</th>
    <th>Carbs serv</th>
    <th>Fruit serv</th>
    <th>Water serv</th>
    <th>Sweets serv</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @diet_plans.each do |diet_plan| %>
  <tr>
		<td><%= diet_plan.diet_name %></td>
    <td><%= diet_plan.veggie_serv %></td>
    <td><%= diet_plan.prot_serv %></td>
    <td><%= diet_plan.carbs_serv %></td>
    <td><%= diet_plan.fruit_serv %></td>
    <td><%= diet_plan.water_serv %></td>
    <td><%= diet_plan.sweets_serv %></td>
    <td><%= link_to 'Show', diet_plan %></td>
    <td><%= link_to 'Edit', edit_diet_plan_path(diet_plan) %></td>
    <td><%= link_to 'Destroy', diet_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Diet plan', new_diet_plan_path %>

app/views/diet_plans/new.html.erb
<h1>New diet_plan</h1>

<%= render 'form' %>

<%= link_to 'Back', diet_plans_path %>

app/views/diet_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Diet Name:</b>
  <%= @diet_plan.diet_name %>
</p>

<p>
  <b>Veggie serv:</b>
  <%= @diet_plan.veggie_serv %>
</p>

<p>
  <b>Prot serv:</b>
  <%= @diet_plan.prot_serv %>
</p>

<p>
  <b>Carbs serv:</b>
  <%= @diet_plan.carbs_serv %>
</p>

<p>
  <b>Fruit serv:</b>
  <%= @diet_plan.fruit_serv %>
</p>

<p>
  <b>Water serv:</b>
  <%= @diet_plan.water_serv %>
</p>

<p>
  <b>Sweets serv:</b>
  <%= @diet_plan.sweets_serv %>
</p>


<%= link_to 'Edit', edit_diet_plan_path(@diet_plan) %> |
<%= link_to 'Back', diet_plans_path %>