config/routes.rb
Fitkids::Application.routes.draw do

  resources :avatars

  devise_for :watchers

  devise_for :children, :controllers => { :sessions => "children/sessions" }

  get "home/index"

  devise_for :users

  resources :child_guardian_relationships do
    resources :users
  end

  resources :users do
    get :child_profile, on: :collection
    get :watcher_profile, on: :collection
    get :sanitized_child_profile, on: :collection
    resources :daily_diets do
      resources :diet_plans
    end
  end

  resources :exercise_reps

  resources :articles

  resources :diet_plans

  resources :daily_diets

  resources :leaderboards do
    get :index_children, on: :collection
  end

  post '/users/increment_exercise'
  post '/users/increment_carbs'
  post '/users/increment_fruit'
  post '/users/increment_prot'
  post '/users/increment_sweets'
  post '/users/increment_veggies'
  post '/users/increment_water'
  post '/users/get_daily_diet'

  root :to => 'home#index'

	

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :content, :name, :topic, :watcher, :article_source, :watcher_id

	belongs_to :watcher, inverse_of: :articles
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new
    @article.watcher = params[:watcher_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_back_to_profile.html.erb
<% if user_signed_in? %>
	<% if current_user.type == "Child" %>
		<%= link_to "Back", child_profile_users_path(:id => current_user.id)%>
	<% elsif current_user.type == "Watcher"%>
		<%= link_to "Back", watcher_profile_users_path(:id => current_user.id)%> 
	<% end %>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :topic %><br />
    <%= f.text_field :topic %>
  </div>
  <div class="field">
    <%= f.label :article_source %><br />
    <%= f.text_area :article_source, :rows=>4 %>
  </div>
    <div class="field">
    <%= f.hidden_field :watcher_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h2>Listing articles</h2>
<br/>

<table>
  <tr>
    <th class="name_col">Name</th>
    <th>Topic</th>
    <th>Content</th>
    <th>Creator</th>
  </tr>

<% @articles.each do |article| %>
  <tr> 
    <td class="name_col"><%= link_to article.name, article.article_source%></td>
    <td><%= article.topic %></td>
    <td><div><%= article.content %></td>
    <td><%= if article.watcher != nil 
              article.watcher.name
            else
              "not found"
            end%></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= render "back_to_profile" %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @article.name %>
</p>

<p>
  <b>Topic:</b>
  <%= @article.topic %>
</p>

<p>
  <b>Article Source:</b>
  <%= @article.article_source %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= render "back_to_profile" %>