config/routes.rb
Fitkids::Application.routes.draw do

  resources :avatars

  devise_for :watchers

  devise_for :children, :controllers => { :sessions => "children/sessions" }

  get "home/index"

  devise_for :users

  resources :child_guardian_relationships do
    resources :users
  end

  resources :users do
    get :child_profile, on: :collection
    get :watcher_profile, on: :collection
    get :sanitized_child_profile, on: :collection
    resources :daily_diets do
      resources :diet_plans
    end
  end

  resources :exercise_reps

  resources :articles

  resources :diet_plans

  resources :daily_diets

  resources :leaderboards do
    get :index_children, on: :collection
  end

  post '/users/increment_exercise'
  post '/users/increment_carbs'
  post '/users/increment_fruit'
  post '/users/increment_prot'
  post '/users/increment_sweets'
  post '/users/increment_veggies'
  post '/users/increment_water'
  post '/users/get_daily_diet'

  root :to => 'home#index'

	

end

app/models/exercise_plan.rb
class ExercisePlan < ActiveRecord::Base
  attr_accessible :ex_title, :goal
  has_many :daily_exercises
end

app/controllers/exercise_plans_controller.rb
class ExercisePlansController < ApplicationController
  # GET /exercise_plans
  # GET /exercise_plans.json
  def index
    @exercise_plans = ExercisePlan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @exercise_plans }
    end
  end

  # GET /exercise_plans/1
  # GET /exercise_plans/1.json
  def show
    @exercise_plan = ExercisePlan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @exercise_plan }
    end
  end

  # GET /exercise_plans/new
  # GET /exercise_plans/new.json
  def new
    @exercise_plan = ExercisePlan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @exercise_plan }
    end
  end

  # GET /exercise_plans/1/edit
  def edit
    @exercise_plan = ExercisePlan.find(params[:id])
  end

  # POST /exercise_plans
  # POST /exercise_plans.json
  def create
    @exercise_plan = ExercisePlan.new(params[:exercise_plan])

    respond_to do |format|
      if @exercise_plan.save
        format.html { redirect_to @exercise_plan, notice: 'Exercise plan was successfully created.' }
        format.json { render json: @exercise_plan, status: :created, location: @exercise_plan }
      else
        format.html { render action: "new" }
        format.json { render json: @exercise_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /exercise_plans/1
  # PUT /exercise_plans/1.json
  def update
    @exercise_plan = ExercisePlan.find(params[:id])

    respond_to do |format|
      if @exercise_plan.update_attributes(params[:exercise_plan])
        format.html { redirect_to @exercise_plan, notice: 'Exercise plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @exercise_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercise_plans/1
  # DELETE /exercise_plans/1.json
  def destroy
    @exercise_plan = ExercisePlan.find(params[:id])
    @exercise_plan.destroy

    respond_to do |format|
      format.html { redirect_to exercise_plans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/exercise_plans_helper.rb
module ExercisePlansHelper
end

app/views/exercise_plans/_form.html.erb
<%= form_for(@exercise_plan) do |f| %>
  <% if @exercise_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise_plan.errors.count, "error") %> prohibited this exercise_plan from being saved:</h2>

      <ul>
      <% @exercise_plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :goal %><br />
    <%= f.number_field :goal %>
  </div>
  <div class="field">
    <%= f.label :ex_title %><br />
    <%= f.text_field :ex_title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercise_plans/edit.html.erb
<h1>Editing exercise_plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise_plan %> |
<%= link_to 'Back', exercise_plans_path %>

app/views/exercise_plans/index.html.erb
<h1>Listing exercise_plans</h1>

<table>
  <tr>
    <th>Goal</th>
    <th>Ex title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @exercise_plans.each do |exercise_plan| %>
  <tr>
    <td><%= exercise_plan.goal %></td>
    <td><%= exercise_plan.ex_title %></td>
    <td><%= link_to 'Show', exercise_plan %></td>
    <td><%= link_to 'Edit', edit_exercise_plan_path(exercise_plan) %></td>
    <td><%= link_to 'Destroy', exercise_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Exercise plan', new_exercise_plan_path %>

app/views/exercise_plans/new.html.erb
<h1>New exercise_plan</h1>

<%= render 'form' %>

<%= link_to 'Back', exercise_plans_path %>

app/views/exercise_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Goal:</b>
  <%= @exercise_plan.goal %>
</p>

<p>
  <b>Ex title:</b>
  <%= @exercise_plan.ex_title %>
</p>


<%= link_to 'Edit', edit_exercise_plan_path(@exercise_plan) %> |
<%= link_to 'Back', exercise_plans_path %>